name: ferro-dashboard
channels:
  - conda-forge
dependencies:
  - python=3.11
  - dash-leaflet
  - dash
  - dash-extensions
  - pyproj
  - pandas
  - shapely
  - geopandas
  - pyarrow
  - plotly
  - waitress
  - fiona